packages:
  - apps/*
  - packages/*
catalog:
  hono: ^4.8.2
  "@orpc/server": ^1.10.0
  "@orpc/openapi": ^1.10.0
  "@orpc/zod": ^1.10.0
  better-auth: ^1.4.0
  dotenv: ^17.2.2
  alchemy: ^0.77.0
  "@orpc/client": ^1.10.0
  "@libsql/client": ^0.14.0
  libsql: ^0.5.22
  "@polar-sh/better-auth": ^1.1.3
  drizzle-orm: ^0.44.2
